### ISSUE TITLE
Adafruit_NAU7802 connected to Arduino Nano 33 IOT

### ISSUE THREAD

**Issue by mhdalassi** [adafruit/Adafruit_NAU7802#10]
Hallo,

I am trying to load the example Code of Adafruit NAU7802 but when its completed the usb port disconnects immediately.
I dont know what the problem. But that also happened with the Arduino Portenta H7.
I am thankful for any suggestions.

**Comment by caternuson** [comment]
This sounds more like a basic program loading issue rather than a library issue. Are you able to upload a basic Blink example sketch OK to these boards?

**Comment by mhdalassi** [comment]
> 

Yes I tryed and it did work.

**Comment by caternuson** [comment]
The sketch you are uploading for the NAU7802 is the example sketch from this library?

Need more information about what is happening here:
```
when its completed the usb port disconnects immediately
```
The sketch compiles and uploads without any errors? But then the COM port disappears and never comes back?

**Comment by mhdalassi** [comment]
> 

Yes that is exactly what is happening

**Comment by caternuson** [comment]
There's nothing special about this sketch or library that would explain that behavior. Have you been able to run other sketches that use `Serial` and see the output in the Arduino Serial Monitor?

**Comment by mhdalassi** [comment]
Yas I did it more than once but this time when I open the serial Monitor the COM port disconnects.

**Comment by caternuson** [comment]
What serial monitor did you open? You said it disappeared after uploading sketch?

**Comment by mhdalassi** [comment]
I am using Arduino IDE 1.8.19 and after the Code has been complied I opend the serial Monitor and befor it opend the error appiers.

**Comment by caternuson** [comment]
It's still confusing what is happening. You say this is happening exactly:
```
the COM port disappears and never comes back
```
But it sounds like there is a COM port showing after the sketch uploads?

**Comment by mhdalassi** [comment]
Yes that what I had in mind. But I did it again and realised that It happend after I tried to open the serial Monitor.
So after uploading the COM port still there.

**Comment by caternuson** [comment]
And then you open the Serial Monitor and see errors?

**Comment by mhdalassi** [comment]
It didn't open and the error showed up

**Comment by caternuson** [comment]
What error messages are you seeing?

**Comment by caternuson** [comment]
Closing due to lack of response.
