### ISSUE TITLE
CircuitPython driver for NAU7802

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_NAU7802#2]
I designed and tested a FeatherWing version of the NAU7802 ADC with a two-channel input. The code folder of the [repo](https://github.com/CedarGroveStudios/NAU7802_24-bit_ADC_FeatherWing) contains a CircuitPython driver partially based on the Adafruit NAU7802 Arduino driver and uses a similar UI. The docs folder contains a "pseudo readthedocs" [document](https://github.com/CedarGroveStudios/NAU7802_24-bit_ADC_FeatherWing/blob/main/docs/pseudo%20readthedocs%20cedargrove_nau7802.pdf) showing the UI.

When the Adafruit board is ready and if it helps, feel free to use any or all of the CircuitPython driver code as needed.

**Comment by ladyada** [comment]
yay congrats! yes we did finisht hardware and then... march happened. oi! would you like to submit the NAU driver either to the community bundle OR we could add it to the adafruit repo and maintain it there (probably better idea so we dont need to involve ya in any bugfixes)

**Comment by CedarGroveStudios** [comment]
I'd prefer to gift it to you "for the cause" so feel free to add it to your repo in any way you see fit. Attribution isn't needed, either. The benefits to me are 1) you and your staff will likely add value to it and make it work even better and 2) support and maintenance for your customer base will be easier and more responsive.

**Comment by ladyada** [comment]
ha ok! will do :) i really outta get back to that breakout :/

**Comment by CedarGroveStudios** [comment]
No reason to rush back to it on my account. I'm good to go.   ;)

**Comment by ladyada** [comment]
ok gonna close this for now!

**Comment by dhalbert** [comment]
Let's open a new issue to get this onto pypi.org, since that's the remaining step.
