### ISSUE TITLE
README.md - wrong link to product image

### ISSUE THREAD

**Issue by timov50** [adafruit/Adafruit_NAU7802#4]
I assume that the line below in the README.md
`<a href="https://www.adafruit.com/product/4226"><img src="assets/board.jpg?raw=true" width="500px"></a>`

should be something like this:
`<a href="https://www.adafruit.com/product/4538"><img src="https://cdn-shop.adafruit.com/product-videos/1024x768/4538-05.jpg?raw=true" width="500px"></a>`

**Comment by evaherrada** [comment]
Fixed

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_NAU7802/commit/5fb7c3ec87ae761de56b1efbd55a8e03ce715dec#commitcomment-76387205
@evaherrada

**Comment by caternuson** [comment]
@evaherrada checkout #8 - was working another issue and was simple PR while i was here

**Comment by caternuson** [comment]
Fixed with #8

**Comment by evaherrada** [comment]
Ah sorry about that. Thanks for catching it!
